services:
  warehouse_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse_api
    ports:
      - "8000:8000"
    depends_on:
      temperature_service:
          condition: service_healthy
    networks:
      - coldnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      timeout: 3s
      retries: 5
      
  temperature_service:
    build:
      context: ./temperature_service
      dockerfile: Dockerfile
    container_name: temperature_service
    ports:
      - "0.0.0.0:8001:8001"
    networks:
      - coldnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/temperatures/freezer"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  coldnet:
    driver: bridge